//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSZ_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budynki
    {
        public string Budynek { get; set; }
        public string Ulica { get; set; }
        public string Numer { get; set; }
        public string Zdjecie { get; set; }
    }
}
