//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSZ_WCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aplikacjaPWSZEntities2 : DbContext
    {
        public aplikacjaPWSZEntities2()
            : base("name=aplikacjaPWSZEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DniZajec> DniZajec { get; set; }
        public virtual DbSet<GrupaLaboratoryjna> GrupaLaboratoryjna { get; set; }
        public virtual DbSet<GrupaWykladowa> GrupaWykladowa { get; set; }
        public virtual DbSet<Kierunki> Kierunki { get; set; }
        public virtual DbSet<Konsultacje> Konsultacje { get; set; }
        public virtual DbSet<Promotor> Promotor { get; set; }
        public virtual DbSet<Rejestracja> Rejestracja { get; set; }
        public virtual DbSet<Rok> Rok { get; set; }
        public virtual DbSet<Specjalnosc> Specjalnosc { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Terminarz> Terminarz { get; set; }
        public virtual DbSet<Wykladowca> Wykladowca { get; set; }
        public virtual DbSet<Zajecia> Zajecia { get; set; }
    }
}
