//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSZ_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rejestracja
    {
        public string NumerIndeksu { get; set; }
        public string Haslo { get; set; }
        public string Kierunek { get; set; }
        public string Rok { get; set; }
        public string GrupaWykladowa { get; set; }
        public string GrupaLaboratoryjna { get; set; }
        public string Promotor { get; set; }
        public string Coockie { get; set; }
        public Nullable<System.DateTime> DateCoockie { get; set; }
    }
}
