//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSZ_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminarz
    {
        public string Dni_rektorskie { get; set; }
        public string Najblizsze_kolokwium { get; set; }
        public string Najblizszy_egzamin { get; set; }
        public string Najblizsze_zaliczenie { get; set; }
    }
}
