//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSZ_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminarz
    {
        public int TerminarzID { get; set; }
        public string Nazwa { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<int> Kierunek { get; set; }
        public Nullable<int> Rok { get; set; }
        public Nullable<int> GrupaWykladowa { get; set; }
        public Nullable<int> GrupaLaboratoryjna { get; set; }
        public Nullable<int> Promotor { get; set; }
    
        public virtual GrupaLaboratoryjna GrupaLaboratoryjna1 { get; set; }
        public virtual GrupaWykladowa GrupaWykladowa1 { get; set; }
        public virtual Kierunki Kierunki { get; set; }
        public virtual Rok Rok1 { get; set; }
    }
}
