//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSZ_WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajecia
    {
        public int ZajeciaID { get; set; }
        public string Kierunek { get; set; }
        public string Rok { get; set; }
        public string Specjalność { get; set; }
        public string GrupaWykladowa { get; set; }
        public string GrupaLaboratoryjna { get; set; }
        public Nullable<System.TimeSpan> GodzinaRozpoczecia { get; set; }
        public Nullable<System.TimeSpan> GodzinaZakonczenia { get; set; }
        public string Przedmiot { get; set; }
        public string TypZajec { get; set; }
        public string Wykładowca { get; set; }
        public string Sala { get; set; }
    }
}
